hc-added feature request template to repo
Github-Community-Standards/github-community-standards pull request #25
Opened 2022-10-31 23:32 UTC by homiecoder

Closes #12

Added feature issue template.

-hc

2022-10-31 23:37 UTC, kjaymiller requested changes
One minor change then you should be good.

2022-10-31 23:37 UTC, kjaymiller commented on .github/ISSUE_TEMPLATE/feature_request.md
> +</br>
It's markdown... breaks are necessary
```suggestion
```

2022-10-31 23:43 UTC, homiecoder commented on .github/ISSUE_TEMPLATE/feature_request.md
> +</br>
ok

2022-11-01 14:44 UTC, kjaymiller commented
Cool go ahead and merge

2022-11-08 17:03 UTC, kjaymiller approved these changes

2022-11-08 17:03 UTC, merged